version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: identifies_ai_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: identifies_ai_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app

  db:
    image: postgres:14
    container_name: identifies_ai_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: identifies_user
      POSTGRES_PASSWORD: identifies_password
      POSTGRES_DB: identifies_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
